version: 0.4.{build}

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

environment:

  GH_TOKEN:
    secure: UEwgLkVFTkytTd8UBEBx959G6VtA7CRMm0bpEQ0pja+7SLTgvFOCSR8mo2vUE3rE

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7 x64
  - yarn install
  - yarn add electron-packager electron-builder@next --dev # force install next version to test electron-builder

build_script:
  - yarn run distWin

test: off