version: 0.4.{build}

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

environment:

  GH_TOKEN:
    secure: It0ZOrM22XNAyzgX/SN/yJTXxV9TxIdMWwCSnCsylg1g84Ft4QLL2JU+6cKDFKcL

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7 x64
  - yarn install
  - yarn add electron-packager electron-builder@next --dev # force install next version to test electron-builder

build_script:
  - yarn run dist

test: off